version: '2'

services:
    pdns-mailcow:
      image: andryyy/mailcow-dockerized:pdns
      volumes:
        - ./data/conf/pdns/:/etc/powerdns/
      restart: always
      networks:
        mailcow-network:
          ipv4_address: 172.22.1.2
          aliases:
            - pdns

    mariadb-mailcow:
      image: mariadb:latest
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/db/mysql/:/var/lib/mysql/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      environment:
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      networks:
        mailcow-network:
          aliases:
            - mysql

    redis-mailcow:
      image: redis
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/db/redis/:/data/
      restart: always
      networks:
        mailcow-network:
          aliases:
            - redis

    rspamd-mailcow:
      image: andryyy/mailcow-dockerized:rspamd
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:ro
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:ro
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - ./data/dkim/txt/:/etc/rspamd/dkim/txt/:ro
        - ./data/dkim/keys/:/etc/rspamd/dkim/keys/:ro
      restart: always
      dns: 
        - 172.22.1.2
        - 127.0.0.11
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - rspamd

    php-fpm-mailcow:
      image: andryyy/mailcow-dockerized:phpfpm
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/dkim/:/shared/dkim/
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      restart: always
      networks:
        mailcow-network:
          aliases:
            - phpfpm

    sogo-mailcow:
      image: andryyy/mailcow-dockerized:sogo
      depends_on:
        - pdns-mailcow
        - mariadb-mailcow
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
      restart: always
      networks:
        mailcow-network:
          aliases:
            - sogo

    rmilter-mailcow:
      image: andryyy/mailcow-dockerized:rmilter
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/rmilter/:/etc/rmilter.conf.d/:ro
      restart: always
      networks:
        mailcow-network:
          aliases:
            - rmilter

    dovecot-mailcow:
      image: andryyy/mailcow-dockerized:dovecot
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/dovecot:/etc/dovecot:ro
        - ./data/vmail:/var/vmail
        - ./data/assets/ssl:/etc/ssl/mail/:ro
      ports:
        - "${IMAP_PORT}:143"
        - "${IMAPS_PORT}:993"
        - "${POP_PORT}:110"
        - "${POPS_PORT}:995"
        - "${SIEVE_PORT}:4190"
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        mailcow-network:
          aliases:
            - dovecot

    postfix-mailcow:
      image: andryyy/mailcow-dockerized:postfix
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/postfix:/opt/postfix/conf:ro
        - ./data/assets/ssl:/etc/ssl/mail/:ro
      ports:
        - "${SMTP_PORT}:25"
        - "${SMTPS_PORT}:465"
        - "${SUBMISSION_PORT}:587"
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      dns: 
        - 172.22.1.2
        - 127.0.0.11
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - postfix

    memcached-mailcow:
      image: memcached
      depends_on:
        - pdns-mailcow
      restart: always
      networks:
        mailcow-network:
          aliases:
            - memcached

    nginx-mailcow:
      depends_on:
        - mariadb-mailcow
        - sogo-mailcow
        - php-fpm-mailcow
      image: andryyy/mailcow-dockerized:nginx
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:ro
      ports:
        - "443:443"
      restart: always
      networks:
        mailcow-network:
          aliases:
            - nginx

networks:
  mailcow-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1

